--- 
- hosts: backups
  gather_facts: no

  handlers:
    - import_tasks: handlers/global.yml

  pre_tasks:
    - name: Include Common
      include_tasks: common.yml

    - name: Set timezone
      timezone:
        name: "{{ TIMEZONE }}"
  
  roles:
  - role: stefangweichinger.ansible_rclone

  vars:
    rclone_config_location: /home/rclone/.config/rclone/rclone.conf
    rclone_configs:
      - name: b2
        properties:
          type: b2
          account: "{{ BACKBLAZE_ACCOUNT }}"
          key: "{{ BACKBLAZE_KEY }}"
      - name: pintail
        properties:
          type: crypt
          remote: b2:pintail
          password: "{{ BACKBLAZE_PASSWORD }}"
          password2: "{{ BACKBLAZE_PASSWORD2 }}"
    
  tasks:
    - name: Create group
      group:
        name:   rclone
        state:  present
        system: true

    - name: Create user
      user:
        name:  rclone
        group: rclone
        createhome: true
    
    - name: Create log directory if it does not exist
      file:
        state: directory
        path: /var/log/rclone
        mode: '0777'
        owner: rclone
        group: rclone

    - name: Create log directory if it does not exist
      file:
        state: touch
        path: /var/log/rclone/rclone.log
        mode: '0644'
        owner: rclone
        group: rclone
    
    - name: Set crontab to execute rclone every day starting at 0400
      cron:
        name: Backup {{ item.folder }} at 04{{ '%02d'|format((index | int) * 10) }}
        user: rclone
        job: >-
          /usr/local/bin/rclone
          --log-file /var/log/rclone/rclone.log
          --log-level INFO
          --fast-list
          --delete-excluded
          {% for i in item.ignore %}--exclude "{{ i }}" {% endfor %}
          sync /mnt/{{ item.folder }} pintail:{{ item.folder }}
        minute: "{{ (index | int) * 10 }}"
        hour: 4
      loop:
        - folder: code
          ignore:
            - node_modules/**
        - folder: config
          ignore:
            - '*.log'
            - /radarr/logs/**
            - /radarr/UpdateLogs/**
            - /sonarr/logs/**
            - /jackett/Jackett/log*
            - /jackett/Jackett/updater*
            - /flexget/received/*
            - /plex/Crash Reports/**
            - /plex/Cache/**
            - /plex/Logs/**
            - /hassio/homeassistant/home-assistant_v2.db
            - /hassio/addons/**
        - folder: skunkworks
          ignore: []
        - folder: users
          ignore: []
        - folder: private
          ignore: []
      loop_control:
        index_var: index
    
    - name: Set properties on config file
      file:
        state: directory
        path: /home/rclone
        recurse: yes
        owner: rclone
        group: rclone