---
- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:
- name: Wait for /var/lib/dpkg/lock to be empty
  wait_for:
    path: /var/lib/dpkg/lock
    search_regex: '\A\Z'

- name: Gather facts
  setup:

# Metrics
- name: Install required system packages for ubuntu
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - gpg
  when: ansible_distribution == 'Ubuntu'

- name: Install required system packages for debian
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - gnupg
    - apt-transport-https
  when: ansible_distribution == 'Debian'

- name: Download Telegraf apt key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    id:  2582E0C5
    state: present

- name: Add Telegraf repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_lsb.codename }} stable"
    filename: telegraf
    state: present
    update_cache: no
    
- name: Install Telegraf
  apt:
    name: telegraf
    update_cache: yes
  notify: restart telegraf

- name: Set Telegraf config
  template:
    src:  templates/metrics/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  vars:
    hostname: "{{ inventory_hostname | regex_replace('.pintail') }}"
  notify: restart telegraf
