---
- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:
- name: Wait for sudo
  become: yes
  shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
- name: Gather facts
  setup:

# Metrics
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - gpg

- name: Download Telegraf apt key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    id:  2582E0C5
    state: present

- name: Add Telegraf repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_lsb.codename }} stable"
    filename: telegraf
    state: present
    
- name: Install Telegraf
  apt:
    name: telegraf
    update_cache: yes
  #notify: restart telegraf

- name: Set Telegraf config
  copy:
    src:  templates/metrics/telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  #notify: restart telegraf

- name: restart telegraf
  service:
    name: telegraf
    state: restarted
    enabled: yes