---
- hosts: files
  gather_facts: no
  pre_tasks:
    - name: Include Common
      include_tasks: common.yml
    - name: Create a admin user for samba
      user:
        name:   admin
        groups: users
        append: yes
    - name: Create a hassio user for samba
      user:
        name:   hassio
        groups: users
        append: yes

    - name: Create users for samba
      user:
        name:   "{{ item.name }}"
        groups: users
        append: yes
      loop: "{{ USERS }}"
      loop_control:
        label: "{{ item.name }}"
      when: "item.password is defined"
    - name: Set samba_users vars
      set_fact:
        samba_users: "{{ samba_users + [ {'name': item.name, 'password': item.password } ] }}"
      loop: "{{ USERS }}"
      loop_control:
        label: "{{ item.name }}"
      when: "item.password is defined"
    - name: Create user share directory
      file:
        path: "/mnt/users/{{ item.name }}"
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'
      loop: "{{ USERS }}"
      loop_control:
        label: "{{ item.name }}"
      when: "item.password is defined"
    - name: Set samba_shares vars
      set_fact:
        samba_shares: "{{ samba_shares + [ {'name': item.name, 'path': '/mnt/users/' + item.name, 'directory_mode': '0777', 'create_mode': '0777', 'valid_users': item.name + ' admin', 'write_list': item.name + ' admin', 'owner': 'nobody', 'group': 'nogroup'} ] }}"
      loop: "{{ USERS }}"
      loop_control:
        label: "{{ item.name }}"
      when: "item.password is defined"

  roles:
  - role: bertvv.samba

  vars:
    samba_workgroup: WORKGROUP
    samba_map_to_guest: bad user
    samba_domain_master: false
    samba_users: 
      - name: admin
        password: "{{ FILES_ADMIN_PWD }}"
      - name: hassio
        password: "{{ ADMIN_PASSWORD }}"
    samba_shares:
      - name: private
        path: /mnt/private
        directory_mode: '0777'
        create_mode:    '0777'
        valid_users: admin
        write_list:  admin
        owner: nobody
        group: nogroup
      
      - name: code
        path: /mnt/code
        force_create_mode: '0777'
        directory_mode: '0777'
        create_mode:    '0777'
        valid_users: admin
        write_list:  admin
        owner: nobody
        group: nogroup
      
      - name: config
        path: /mnt/config
        force_create_mode: '0777'
        directory_mode:    '0777'
        create_mode:       '0777'
        valid_users: admin 
        write_list:  admin
        owner: nobody
        group: nogroup
      
      - name: storage
        path: /mnt/storage
        force_create_mode: '0777'
        directory_mode:    '0777'
        create_mode:       '0777'
        valid_users: admin 
        write_list:  admin
        owner: nobody
        group: nogroup
      
      - name: downloads
        path: /mnt/downloads
        directory_mode: '0777'
        create_mode:    '0777'
        valid_users: admin
        write_list:  admin
        owner: nobody
        group: nogroup
      
      - name: hassio-config
        path: /mnt/config/hassio
        force_create_mode: '0777'
        directory_mode:    '0777'
        create_mode:       '0777'
        valid_users: hassio admin 
        write_list:  hassio admin
        owner: nobody
        group: nogroup
      
      - name: skunkworks
        path: /mnt/skunkworks
        directory_mode: '0777'
        create_mode:    '0777'
        owner: nobody
        group: nogroup
        public:    'yes'
        writable:  'yes'
        read_only: 'no'
        guest_ok:  'yes'
      
      - name: torrents
        path: /mnt/torrents
        directory_mode: '0777'
        create_mode:    '0777'
        owner: nobody
        group: nogroup
        public:    'yes'
        writable:  'yes'
        read_only: 'no'
        guest_ok:  'yes'

      - name: media
        path: /mnt/media
        directory_mode: '0777'
        create_mode:    '0777'
        owner: nobody
        group: nogroup
        public:    'yes'
        writable:  'yes'
        read_only: 'no'
        guest_ok:  'yes'
