---
- hosts: flexget
  gather_facts: no

  handlers:
    - import_tasks: handlers/global.yml
    - name:    reload systemctl
      command: systemctl daemon-reload

  pre_tasks:
    - name: Include Common
      include_tasks: common.yml
      
  tasks:
    - name: Install required system packages
      apt:  name={{ item }} state=latest update_cache=yes
      loop:
        - gpg
        - python3
        - python3-pip

    - name: Create group
      group:
        name:   flexget
        state:  present
        system: true

    - name: Create user
      user:
        name:  flexget
        group: flexget
        createhome: false
    
    - name: Install Flexget
      pip:
        name: flexget

    - name: Create log directory if it does not exist
      file:
        path: /var/log/flexget
        state: directory
        mode: '0755'
        owner: flexget
        group: flexget
    
    - name: Set crontab to execute Flexget every 5 minutes
      cron:
        name: Execute Flexget
        user: flexget
        job: >-
          /usr/local/bin/flexget --cron
          -l /var/log/flexget/flexget.log
          -c /mnt/config/flexget/config.yml
          execute
        minute: "*/5"