---
- hosts: home
  gather_facts: no
  handlers:
    - import_tasks: handlers/global.yml
  roles:
    - geerlingguy.docker

  pre_tasks:
    - name: Include Common
      include_tasks: common.yml

    - name: Reboot for USB Hub
      local_action: 
        module: shell
        _raw_params: |
          ssh -oStrictHostKeyChecking=no root@proxmox.pintail 'qm reboot 10010'
    
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:    

    - name: Search for USB Hub
      shell: cat /sys/bus/usb/devices/*/product | grep -e HubZ
      register: usb_hub
      failed_when: usb_hub.rc != 0
    
    - name: Install iptables-persistent
      include_tasks: tasks/install-iptables-persistent.yml

  tasks:  
    - name: Install required system packages
      apt:  name={{ item }} state=latest update_cache=yes
      loop:
        - software-properties-common
        - pulseaudio
        - apparmor-utils
        - apt-transport-https
        - avahi-daemon
        - ca-certificates
        - curl
        - dbus
        - jq
        - network-manager
        - socat
        - cifs-utils
        - expect

    - name: Place Samba credentials file
      copy:
        content: |
          username=hassio
          password={{ ADMIN_PASSWORD }}
        dest: /root/.smbcredentials
        mode: 0600

    - name: Mount config directory
      mount:
        state:  mounted
        fstype: cifs
        path:   /usr/share/hassio
        src:    //{{ hostvars['files.pintail']['ansible_host'] }}/hassio-config
        opts:   credentials=/root/.smbcredentials,nobrl

    - name: Disable ModemManager
      systemd:
        name:    ModemManager
        state:   stopped
        enabled: no

    - include_tasks: tasks/forward-port.yml
      vars:
        in_port:  '80'
        out_port: '8123'

    - name: Set DNS config in resolv.conf
      copy:
        content: |
          nameserver 192.168.47.1
        dest: /etc/resolvconf/resolv.conf.d/base      
    
    - name: Get latest os-agent info
      uri:
        url: https://api.github.com/repos/home-assistant/os-agent/releases/latest
        return_content: true
      register: osagent_latest

    - name: Download os-agent
      get_url:
        url: "https://github.com/home-assistant/os-agent/releases/download/{{ osagent_latest.json.name }}/os-agent_{{ osagent_latest.json.name }}_linux_x86_64.deb"
        dest: /home/debian/os-agent-{{ osagent_latest.json.name }}.deb

    - name: Install os-agent
      apt: deb="/home/debian/os-agent-{{ osagent_latest.json.name }}.deb"

    - name: Check that os-agent installed
      shell: gdbus introspect --system --dest io.hass.os --object-path /io/hass/os
    
    - name: Download Home Assistant Debian Package
      get_url:
        url: https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
        dest: /home/debian/homeassistant-supervised.deb

    - name: Install Home Assistant
      apt: deb="/home/debian/homeassistant-supervised.deb"
