---
- hosts: home
  gather_facts: no
  pre_tasks:
    - name: Include Common
      include_tasks: common.yml
  
  roles:
    - geerlingguy.docker
  
  tasks:  
    - name: Install required system packages
      apt:  name={{ item }} state=latest update_cache=yes
      loop:
        - software-properties-common
        - pulseaudio
        - apparmor-utils
        - apt-transport-https
        - avahi-daemon
        - ca-certificates
        - curl
        - dbus
        - jq
        - network-manager
        - socat
        - cifs-utils
        - netfilter-persistent

    - name: Place Samba credentials file
      copy:
        content: |
          username=hassio
          password={{ ADMIN_PASSWORD }}
        dest: "/root/.smbcredentials"
        mode: 0600

    - name: Mount config directory
      mount:
        state:  mounted
        fstype: cifs
        path:   /usr/share/hassio
        src:    //{{ hostvars['files.pintail']['ansible_host'] }}/hassio-config
        opts:   credentials=/root/.smbcredentials

    - name: Disable ModemManager
      systemd:
        name:    ModemManager
        state:   stopped
        enabled: no

    - name: Forward port 80 to 8123
      iptables:
        table:    nat
        chain:    PREROUTING
        jump:     REDIRECT
        protocol: tcp
        match:    tcp
        in_interface: eth0
        destination_port: '80'
        to_ports: '8123'
      register: iptables
    
    - name: Save iptables
      shell: service netfilter-persistent save
      when: iptables.changed
    
    - name: Install home assistant supervised
      shell: |
        curl -sL "https://raw.githubusercontent.com/home-assistant/installer/master/installer.sh" | bash -s