---
- hosts: home
  gather_facts: no
  handlers:
    - import_tasks: handlers/global.yml
  roles:
    - geerlingguy.docker

  pre_tasks:
    - name: Include Common
      include_tasks: common.yml

    - name: Reboot for USB Hub
      local_action: 
        module: shell
        _raw_params: |
          ssh -oStrictHostKeyChecking=no root@proxmox.pintail 'qm reboot 10010'
    
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:    

    - name: Search for USB Hub
      shell: cat /sys/bus/usb/devices/*/product | grep -e HubZ
      register: usb_hub
      failed_when: usb_hub.rc != 0
    
    - name: Install iptables-persistent
      include_tasks: tasks/install-iptables-persistent.yml

  tasks:  
    - name: Install required system packages
      apt:  name={{ item }} state=latest update_cache=yes
      loop:
        - software-properties-common
        - pulseaudio
        - apparmor-utils
        - apt-transport-https
        - avahi-daemon
        - ca-certificates
        - curl
        - dbus
        - jq
        - network-manager
        - socat
        - cifs-utils
        - expect

    - name: Place Samba credentials file
      copy:
        content: |
          username=hassio
          password={{ ADMIN_PASSWORD }}
        dest: "/root/.smbcredentials"
        mode: 0600

    - name: Mount config directory
      mount:
        state:  mounted
        fstype: cifs
        path:   /usr/share/hassio
        src:    //{{ hostvars['files.pintail']['ansible_host'] }}/hassio-config
        opts:   credentials=/root/.smbcredentials,nobrl

    - name: Disable ModemManager
      systemd:
        name:    ModemManager
        state:   stopped
        enabled: no

    - include_tasks: tasks/forward-port.yml
      vars:
        in_port:  '80'
        out_port: '8123'
    
    - name: Download installer.sh
      get_url:
        url: https://raw.githubusercontent.com/home-assistant/installer/master/installer.sh
        dest: /home/debian/installer.sh
    
    - name: Install home assistant supervised
      shell: |
        set timeout 300
        spawn /bin/bash installer.sh
        expect "*N/y"
        send "y\n"
        expect eof
      args:
        executable: /usr/bin/expect