---
- hosts: metrics
  gather_facts: no
  vars:
    grafana_data_dir: /mnt/storage/grafana/data
    grafana_security:
      admin_user: admin
      admin_password: "{{ ADMIN_PASSWORD }}"
    grafana_datasources:
      - name: InfluxDB
        type: influxdb
        database: telegraf
        access: proxy
        url: http://localhost:8086
    grafana_dashboards:
      - dashboard_id: 928
        revision_id: 4
        datasource: InfluxDB
      - dashboard_id: 12034
        revision_id: 1
        datasource: InfluxDB
    influxdb_data_dir: /mnt/storage/influxdb/data
    influxdb_meta_dir: /mnt/storage/influxdb/meta

  handlers:
    - import_tasks: handlers/global.yml
  
  pre_tasks:
    - name: Include Common
      include_tasks: common.yml
    
  roles:
    - role: ansible-influxdb
    - role: cloudalchemy.grafana

  tasks:
    - name: Install required system packages
      apt:  name={{ item }} state=latest update_cache=yes
      loop:
        - python3
        - python3-pip

    - name: Install pip dependencies
      pip: name={{ item }}
      loop:
        - requests
        - influxdb

    - name: Wait for influxdb to come up
      wait_for:
        port:  8086
        delay: 1

    - name: Create telegraf database
      influxdb_database:
        database_name: telegraf
        use_udp: no
        udp_port: 0
        port: 8086

    - name: create 60 day retention policy
      influxdb_retention_policy:
        database_name: telegraf
        policy_name: autogen
        duration: 60d
        replication: 1
        use_udp: no
        udp_port: 0
        port: 8086