--- 
- hosts: pihole
  gather_facts: no
  pre_tasks:
    - name: Include Common
      include_tasks: common.yml
  
  roles:
  - role: drew-kun.pihole
    pihole_setupVars_conf_WEBPASSWD: "{{ PI_ADMIN_PASSWORD }}"
    pihole_dnsmasq_custom_conf: ""
    pihole_setupVars_conf: |
      DNSMASQ_LISTENING=single
      DNS_FQDN_REQUIRED=true
      DNS_BOGUS_PRIV=true
      DNSSEC=true
      TEMPERATUREUNIT=C
      WEBUIBOXEDLAYOUT=traditional
      API_EXCLUDE_DOMAINS=
      API_EXCLUDE_CLIENTS=
      API_QUERY_LOG_SHOW=all
      API_PRIVACY_MODE=false
      PIHOLE_INTERFACE=eth0
      IPV4_ADDRESS={{ hostvars['pihole.pintail']['ansible_default_ipv4']['address'] }}
      PIHOLE_DNS_1=8.8.8.8
      PIHOLE_DNS_2=8.8.4.4
      QUERY_LOGGING=true
      INSTALL_WEB_SERVER=true
      INSTALL_WEB_INTERFACE=true
      LIGHTTPD_ENABLED=true
      BLOCKING_ENABLED=true
      