# Infra
- import_playbook: vpn.yml
- import_playbook: pihole.yml
- import_playbook: files.yml
- import_playbook: metrics.yml

# Home
- import_playbook: home.yml

# My stuff
- import_playbook: code.yml
- import_playbook: octopi.yml

# Media
- import_playbook: torrents.yml
- import_playbook: plex.yml
- import_playbook: sonarr.yml
- import_playbook: radarr.yml
- import_playbook: jackett.yml
- import_playbook: flexget.yml