---
- hosts: sonarr
  gather_facts: no
  
  handlers:
    - import_tasks: handlers/global.yml
    - name: Reload Sonarr service config
      command: systemctl daemon-reload
    - name: Restart Sonarr service
      service: 
        name:  mysonarr
        state: restarted

  pre_tasks:
    - name: Include Common
      include_tasks: common.yml
    - name: Install iptables-persistent
      include_tasks: tasks/install-iptables-persistent.yml
    - name: Install mono-dev
      include_tasks: tasks/install-mono.yml

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        - gpg
        - libmediainfo0v5
    
    - name: Create group
      group:
        name:  sonarr
        state: present

    - name: Create user
      user:
        name:  sonarr
        group: sonarr
        createhome: false

    - name: Ensure the Sonarr GPG key has been imported
      apt_key:
        url:   http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2009837CBFFD68F45BC180471F4F90DE2A9B4BF8
        state: present
    
    - name: Ensure the Sonarr repository is present
      apt_repository:
        repo:  deb http://apt.sonarr.tv/ubuntu bionic main
        state: present

    # Prevent apt from writing a service file
    - name: Create symbolic link 
      file:
        src: /dev/null
        dest: /etc/systemd/system/sonarr.service
        state: link

    - name: Install Sonarr
      apt:
        name: sonarr

    - include_tasks: tasks/forward-port.yml
      vars:
        in_port:  '80'
        out_port: '8989'
    
    - name: Deploy Sonarr service manifest
      template:
        src: sonarr/service.j2
        dest: /etc/systemd/system/mysonarr.service
        owner: root
        group: root
        mode: 0600
      notify:
        - Reload Sonarr service config
        - Restart Sonarr service
    
    - name: Ensure the Sonarr service is running and enabled on boot
      service:
        name: mysonarr 
        state: started
        enabled: yes
        daemon_reload: yes