---
- hosts: sonarr
  gather_facts: no
  
  handlers:
    - name: Reload Sonarr service config
      command: "systemctl daemon-reload"
    - name: Restart Sonarr service
      service: 
        name: sonarr
        state: restarted

  pre_tasks:
    - name: Include Common
      include_tasks: common.yml

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        - gpg
        - libmediainfo0v5
    
    - name: Create group
      group:
        name: sonarr
        state: present

    - name: Create user
      user:
        name: sonarr
        group: sonarr
        createhome: false

    - name: Ensure the Mono GPG key has been imported
      apt_key:
        state: present
        url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

    - name: Ensure the Mono Xamarin APT repository is present
      apt_repository:
        repo: deb http://download.mono-project.com/repo/debian stable-bionic main
        state: present
    
    - name: Install Mono
      apt:
        name: mono-devel

    - name: Ensure the Sonarr GPG key has been imported
      apt_key:
        state: present
        url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA236C58F409091A18ACA53CBEBFF6B99D9B78493
    
    - name: Ensure the Sonarr repository is present
      apt_repository:
        repo: deb http://apt.sonarr.tv/ master main
        state: present

    - name: Install Sonarr
      apt:
        name: nzbdrone

    - name: Forward port 80 to 8989
      iptables:
        table: nat
        chain: PREROUTING
        jump: REDIRECT
        protocol: tcp
        match: tcp
        in_interface: eth0
        destination_port: '80'
        to_ports: '8989'
    
    - name: Deploy Sonarr service manifest
      template:
        src: sonarr/service.j2
        dest: /etc/systemd/system/sonarr.service
        owner: root
        group: root
        mode: 0600
      notify:
        - Reload Sonarr service config
        - Restart Sonarr service
    
    - name: Ensure the Sonarr service is running and enabled on boot
      service:
        name: sonarr 
        state: started
        enabled: yes