---
- hosts: vpn
  gather_facts: no
  pre_tasks:
    - name: Include Common
      include_tasks: common.yml
  vars:
    wireguard_preup:
      - echo 1 > /proc/sys/net/ipv4/ip_forward
  roles:
  - role: ansible-role-wireguard