---
- hosts: vpn
  gather_facts: no
  pre_tasks:
    - name: Include Common
      include_tasks: common.yml
    - name: Forward Traffic
      sysctl:
        name:       net.ipv4.ip_forward
        value:      '1'
        sysctl_set: yes
  
  roles:
  - role: ansible-role-wireguard